# audio
define audio.deepspace = "audio/DeepSpace.mp3"
define audio.solace = "audio/Solace.mp3"
define audio.november = "audio/November.mp3"
define audio.whales = "audio/Whales.mp3"
define audio.lounge = "audio/The_Lounge.mp3"
define audio.coolride = "audio/CoolRide.mp3"
define audio.corporationmotivation = "audio/CorporationMotivation.mp3"
define audio.different = "audio/Different.mp3"
define audio.goodvibes = "audio/GoodVibes.mp3"
define audio.interconnected = "audio/Interconnected.mp3"
define audio.drifting2 = "audio/Drifting2.mp3"
