define me = Character('Я', color="#2E8B57")
define enj = Character('Энджи', color="#7B68EE")
define phil = Character('Фил', color="#F0FFFF")
define key = Character('Кей', color="#8B008B")
define nat = Character('Натали', color="#B0E0E6")
define v = Character('Голос', color="#ffffff")
define sp = Character('Диктор', color="#c8ffc8")
define wa = Character('Официант', color="#c8ffc8")

define un = Character('?', color="#8B008B")
define un_e = Character('?', color="#7B68EE")
define un_p = Character('?', color="#F0FFFF")
define un_n = Character('?', color="#B0E0E6")
define un_s = Character('?', color="#FFE4E1")
define syst = Character('system', color="#B0E0E6")

